# PATHS
RESOURCE_PATH = "src/res/"
ICON_BASE_PATH = RESOURCE_PATH+"icons/"
STRATAGEM_ICON_PATH = ICON_BASE_PATH+"stratagems/"
FONT_BASE_PATH = RESOURCE_PATH+"fonts/"
SETTINGS_PATH = "settings.json"
LOADOUTS_PATH = "loadouts.json"

# FACTORY CONSTANTS
## VIEWS
VIEW_PYQT5 = "pyqt5"

## EXECUTORS
EXECUTOR_PYNPUT = "pynput"
EXECUTOR_PYAUTOGUI = "pyautogui"
EXECUTOR_ARDUINO = "arduino"
EXECUTOR_XDOTOOL = "xdotool"
EXECUTOR_PICO = "pico"

# SETTINGS CONSTANTS
## GLOBAL ARM
ARM_MODE_PUSH = "push"
ARM_MODE_TOGGLE = "toggle"

## EXECUTORS
SETTINGS_VALUE_TYPE_INT = "Integer"
SETTINGS_VALUE_TYPE_BOOL = "Boolean"
SETTINGS_VALUE_TYPE_HEADER = "Header"

MENU_TYPE_MENU = "Menu"
MENU_TYPE_ACTION = "Action"

# COLORS
COLOR_STRATAGEM_BACKGROUND = "#ff1f2832"
COLOR_SETTINGS_HEADLINE_BACKGROUND = "#FFe6e6e4"