# PATHS
RESOURCE_PATH = "src/res/"
ICON_BASE_PATH = RESOURCE_PATH+"icons/"
STRATEGEM_ICON_PATH = ICON_BASE_PATH+"strategems/"
SETTINGS_PATH = "settings.json"

# FACTORY CONSTANTS
## VIEWS
VIEW_PYQT5 = "pyqt5"

## EXECUTORS
EXECUTOR_PYNPUT = "pynput"
EXECUTOR_PYAUTOGUI = "pyautogui"
EXECUTOR_ARDUINO = "arduino"
EXECUTOR_XDOTOOL = "xdotool"

# SETTINGS CONSTANTS
## GLOBAL ARM
ARM_MODE_PUSH = "push"
ARM_MODE_TOGGLE = "toggle"