# PATHS
RESOURCE_PATH = "src/res/"
ICON_BASE_PATH = RESOURCE_PATH+"icons/"
STRATAGEM_ICON_PATH = ICON_BASE_PATH+"stratagems/"
SETTINGS_PATH = "settings.json"

# FACTORY CONSTANTS
## VIEWS
VIEW_PYQT5 = "pyqt5"

## EXECUTORS
EXECUTOR_PYNPUT = "pynput"
EXECUTOR_PYAUTOGUI = "pyautogui"
EXECUTOR_ARDUINO = "arduino"
EXECUTOR_XDOTOOL = "xdotool"

# SETTINGS CONSTANTS
## GLOBAL ARM
ARM_MODE_PUSH = "push"
ARM_MODE_TOGGLE = "toggle"

# COLORS
COLOR_STRATAGEM_BACKGROUND = "#ff1f2832"
COLOR_SETTINGS_HEADLINE_BACKGROUND = "#FFe6e6e4"