name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ci-pipeline.yml
          commit: ${{ github.sha }}
          name: hellsnake-windows.exe
          path: .
      - name: Rename artifact
        run: mv hellsnake-windows.exe hellsnake.exe
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: hellsnake.exe
          generate_release_notes: true