name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format github --target-version py310 .
        continue-on-error: true
      - name: Create virtual display for tests
        run: |
          pip install pyvirtualdisplay
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Test with pytest
        run: |
          pip install pytest coverage
          export DISPLAY=:99.0
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
